name: Deploy to Production

on:
  push:
    branches:
     - main

jobs:
    deploy_prod:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          
        - name: Login to GitHub Container Registry
          run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

        - name: Build and Push Docker Image to GHCR
          run: |
            REPO_SERVER_NAME="ghcr.io/miguelcmaurer/permit_checker_server"
            echo "🚀 Building API server..."
            docker build -t $REPO_SERVER_NAME .
            echo "🚀 Pushing images to GHCR..."
            docker push $REPO_SERVER_NAME
        
        - name: Push to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: root
            key: ${{ secrets.SERVER_KEY }}
            script: |
              #!/bin/bash
              set -e  # Exit immediately if a command fails
              
              ENV_FILE="/home/ubuntu/.env"
              
              echo "✅ Ensuring .env file exists"
              if [ ! -f "$ENV_FILE" ]; then
                echo "ERROR: .env file is missing on server!" >&2
                exit 1
              fi
              
              echo "✅ Logging into GHCR & pulling latest Docker image"
              docker login ghcr.io -u "${{ github.actor }}" --password ${{ secrets.GHCR_PAT }}
              docker pull ghcr.io/miguelcmaurer/permit_checker_server:latest
              
              echo "✅ Stopping old container"
              docker stop chill_zone_server || true
              docker rm chill_zone_server || true
              
              echo "✅ Starting new container"
              docker run -d --name whitney_server_server --env-file /home/ubuntu/.env -p 8080:8080 ghcr.io/miguelcmaurer/permit_checker_server:latest
